
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
import java.sql.*;
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PF1 = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HOMEPAGE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("USER NAME :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 190, 210, 40);

        TF1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF1);
        TF1.setBounds(780, 190, 180, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("PASSWORD :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 370, 200, 44);

        PF1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(PF1);
        PF1.setBounds(780, 360, 180, 40);

        LOGIN.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        LOGIN.setText("LOGIN");
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN);
        LOGIN.setBounds(620, 630, 200, 100);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 52)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMIN LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 30, 650, 110);

        HOMEPAGE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        HOMEPAGE.setText("HOME PAGE");
        HOMEPAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEPAGEActionPerformed(evt);
            }
        });
        getContentPane().add(HOMEPAGE);
        HOMEPAGE.setBounds(1120, 20, 280, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
String sql=" Select * from admin "; 
try { 
    Class.forName("java.sql.Driver"); 
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/flight","root","1234"); 
    Statement st = con.createStatement(); 
    Statement st1 = con.createStatement(); 
    ResultSet rs = st.executeQuery(sql); 
    String user=TF1.getText(); 
    String pwd= new String (PF1.getPassword()); 
    while(rs.next()) { 
        String uname=rs.getString("USERNAME"); 
        String password=rs.getString("PASSWORD");
        if ((user.equals(uname)) && (pwd.equals(password))) { 
         new Admin().setVisible(true);
         dispose();
        }
        else if((user.equals(null)) &&(password.equals(null))){
            JOptionPane.showMessageDialog(null,"Please Enter Username And Password!!!!!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Wrong Credentials!!  Please Try Again!");
        }
    }
}
catch (Exception e) { 
    JOptionPane.showMessageDialog(this, e.getMessage()); 
}
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINActionPerformed

    private void HOMEPAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEPAGEActionPerformed
        new MainForm().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_HOMEPAGEActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
TF1.requestFocus(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HOMEPAGE;
    private javax.swing.JButton LOGIN;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JTextField TF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
