

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INTERNATIONAL = new javax.swing.JButton();
        BOOKED = new javax.swing.JButton();
        DOMESTIC = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(null);

        INTERNATIONAL.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        INTERNATIONAL.setText("Show International Flights");
        INTERNATIONAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INTERNATIONALActionPerformed(evt);
            }
        });
        getContentPane().add(INTERNATIONAL);
        INTERNATIONAL.setBounds(40, 230, 650, 69);

        BOOKED.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        BOOKED.setText("Show Booked Tickets");
        BOOKED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKEDActionPerformed(evt);
            }
        });
        getContentPane().add(BOOKED);
        BOOKED.setBounds(440, 610, 550, 69);

        DOMESTIC.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        DOMESTIC.setText("Show Domestic Flights");
        DOMESTIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOMESTICActionPerformed(evt);
            }
        });
        getContentPane().add(DOMESTIC);
        DOMESTIC.setBounds(750, 230, 610, 69);

        LOGOUT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(1130, 10, 280, 40);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INTERNATIONALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INTERNATIONALActionPerformed
try { 
    new Flights().setVisible(true);
    dispose();
    DefaultTableModel tm=(DefaultTableModel)Flights.T1.getModel();
    Class.forName("java.sql.DriverManager"); 
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/flight", "root","1234"); 
   Statement st = con.createStatement();
    String query="Select * from internationalflights where Date>=curDate()order by date;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        Object ob[]={rs.getDate(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7),rs.getString(8)};
        tm.addRow(ob);
    }
} 
catch (Exception e) { 
    JOptionPane.showMessageDialog(null, e.getMessage()); 
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_INTERNATIONALActionPerformed

    private void DOMESTICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOMESTICActionPerformed
try { 
    new Flights().setVisible(true);
    dispose();
    DefaultTableModel tm=(DefaultTableModel)Flights.T1.getModel();
    Class.forName("java.sql.DriverManager"); 
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/flight", "root","1234"); 
   Statement st = con.createStatement();
    String query="Select * from domesticflights where Date>=curDate()order by date;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        Object ob[]={rs.getDate(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7),rs.getString(8)};
        tm.addRow(ob);
    }
} 
catch (Exception e) { 
    JOptionPane.showMessageDialog(null, e.getMessage()); 
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_DOMESTICActionPerformed

    private void BOOKEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKEDActionPerformed
try { 
    new BookedTickets().setVisible(true);
    dispose();
    DefaultTableModel tm=(DefaultTableModel)BookedTickets.T1.getModel();
    Class.forName("java.sql.DriverManager"); 
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/flight", "root","1234"); 
   Statement st = con.createStatement();
    String query="Select * from reserved order by date asc;";
    ResultSet rs=st.executeQuery(query);
    while(rs.next()){
        Object ob[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getInt(10)};
        tm.addRow(ob);
    }
} 
catch (Exception e) { 
    JOptionPane.showMessageDialog(null, e.getMessage()); 
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKEDActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        new MainForm().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOKED;
    private javax.swing.JButton DOMESTIC;
    private javax.swing.JButton INTERNATIONAL;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
