

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
public class BookFlights extends javax.swing.JFrame {
  

    /**
     * Creates new form BookingForm
     */
    public BookFlights() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox<>();
        CB2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        CB3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CB4 = new javax.swing.JComboBox<>();
        SHOWFLIGHTS = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.addTab("VIEW FLIGHT DEATILS", jTabbedPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK FLIGHTS");
        setMinimumSize(new java.awt.Dimension(1440, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 52)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT  ORIGIN  AND  DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 980, 64);

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        R1.setText("INTERNATIONAL");
        R1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1);
        R1.setBounds(600, 190, 290, 50);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("FROM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 300, 110, 44);

        CB1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Singapore", "Dubai", "Los Angeles", "London", "Delhi", "Kolkata", "Mumbai", "Chennai" }));
        CB1.setFocusable(false);
        getContentPane().add(CB1);
        CB1.setBounds(460, 300, 158, 36);

        CB2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        CB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Singapore", "Dubai", "Los Angeles", "London", "Delhi", "Kolkata", "Mumbai", "Chennai" }));
        getContentPane().add(CB2);
        CB2.setBounds(890, 300, 158, 36);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setText("TO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 300, 50, 44);

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        R2.setText("DOMESTIC");
        R2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2);
        R2.setBounds(660, 550, 185, 53);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setText("FROM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 640, 110, 44);

        CB3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        CB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Delhi", "Kolkata", "Mumbai", "Chennai", "Srinagar", "Pune" }));
        getContentPane().add(CB3);
        CB3.setBounds(470, 640, 180, 36);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setText("TO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 640, 50, 44);

        CB4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        CB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Delhi", "Kolkata", "Mumbai", "Chennai", "Srinagar", "Pune" }));
        getContentPane().add(CB4);
        CB4.setBounds(910, 640, 160, 36);

        SHOWFLIGHTS.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        SHOWFLIGHTS.setText("SHOW FLIGHTS");
        SHOWFLIGHTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWFLIGHTSActionPerformed(evt);
            }
        });
        getContentPane().add(SHOWFLIGHTS);
        SHOWFLIGHTS.setBounds(510, 780, 460, 70);

        LOGOUT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(1140, 10, 280, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
CB1.setEnabled(false);
CB2.setEnabled(false);
CB3.setEnabled(false);
CB4.setEnabled(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
CB1.setEnabled(true);
CB2.setEnabled(true);
CB3.setEnabled(false);
CB4.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
CB3.setEnabled(true);
CB4.setEnabled(true);
CB1.setEnabled(false);
CB2.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_R2ActionPerformed

    private void SHOWFLIGHTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWFLIGHTSActionPerformed
try{
    if((R1.isSelected()==true && CB1.getSelectedItem()=="Select") || (R2.isSelected()==true && CB3.getSelectedItem()=="Select")  ){
        JOptionPane.showMessageDialog(null,"Please Select Origin");     
    }
    else if((R1.isSelected()==true && CB2.getSelectedItem()=="Select") || (R2.isSelected()==true && CB4.getSelectedItem()=="Select")  ){
        JOptionPane.showMessageDialog(null,"Please Select Destination");
    }
    else{
    new FlightDetails().setVisible(true);
    dispose();
    String sql="";
    if(R1.isSelected()==true){
      sql="Select * from internationalflights where Origin='"+CB1.getSelectedItem()+"' and Destination='"+CB2.getSelectedItem()+"' && Date>=curDate() order by date;";
     
    }
      else if(R2.isSelected()==true){
        sql="Select * from domesticflights where Origin='"+CB3.getSelectedItem()+"' and Destination='"+CB4.getSelectedItem()+"' && Date>=curDate() order by date;";
       
      }
DefaultTableModel tm=(DefaultTableModel)FlightDetails.T1.getModel();
Class.forName("com.mysql.jdbc.Driver"); 
Connection con= DriverManager.getConnection("jdbc:mysql://localhost/flight","root","1234");
Statement st =con.createStatement();
ResultSet rs =st.executeQuery(sql);
    System.out.println(sql);
while(rs.next()){
    Object ob[]={rs.getDate(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7),rs.getString(8)};
     tm.addRow(ob);
     if(tm.getRowCount()==0){
         JOptionPane.showMessageDialog(null,"No Flights Available On This Route!!");
     }
} 
    }
}
catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_SHOWFLIGHTSActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        new MainForm().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookFlights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> CB1;
    public static javax.swing.JComboBox<String> CB2;
    public static javax.swing.JComboBox<String> CB3;
    public static javax.swing.JComboBox<String> CB4;
    private javax.swing.JButton LOGOUT;
    public static javax.swing.JRadioButton R1;
    public static javax.swing.JRadioButton R2;
    private javax.swing.JButton SHOWFLIGHTS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
