
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
import java.sql.*;
public class ConfirmDetails extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    
    public ConfirmDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        RESERVE = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TF8 = new javax.swing.JTextField();
        TF11 = new javax.swing.JTextField();
        TF9 = new javax.swing.JTextField();
        TF10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 52)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("JOURNEY DETAILS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 10, 840, 64);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel4.setText("NAME OF PASSENGER :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 110, 300, 40);

        TF1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF1);
        TF1.setBounds(890, 110, 180, 36);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel5.setText("CONTACT NO. :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 160, 340, 40);

        TF2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF2);
        TF2.setBounds(890, 160, 180, 36);

        RESERVE.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        RESERVE.setText("RESERVE");
        RESERVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESERVEActionPerformed(evt);
            }
        });
        getContentPane().add(RESERVE);
        RESERVE.setBounds(390, 730, 270, 90);

        LOGOUT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(730, 730, 330, 90);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel6.setText("SEATS BOOKED :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 310, 210, 40);

        TF3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF3);
        TF3.setBounds(890, 210, 180, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel7.setText("DEPARTURE TIME :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 360, 240, 50);

        TF4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF4);
        TF4.setBounds(890, 260, 180, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel8.setText("DATE :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 410, 120, 40);

        TF5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF5);
        TF5.setBounds(890, 310, 180, 36);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel9.setText("FROM :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 460, 120, 40);

        TF6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF6);
        TF6.setBounds(890, 360, 180, 36);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel10.setText("TO :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 510, 90, 40);

        TF7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF7);
        TF7.setBounds(890, 410, 180, 36);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel11.setText("PAYMENT METHOD :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 610, 280, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setText("TOTAL AMOUNT :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 560, 230, 40);

        TF8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF8);
        TF8.setBounds(890, 460, 180, 36);

        TF11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF11);
        TF11.setBounds(890, 610, 180, 36);

        TF9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF9);
        TF9.setBounds(890, 510, 180, 36);

        TF10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF10);
        TF10.setBounds(890, 560, 180, 36);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel2.setText("AIRLINE :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 210, 140, 40);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel13.setText("CLASS :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 260, 120, 40);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel12.setText("UNIQUE CODE :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 660, 210, 40);

        TF12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF12);
        TF12.setBounds(890, 660, 180, 36);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel14.setText("*Enter a 8 digit numeric code ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1080, 670, 300, 30);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("*Unique Code Can Be Used To View Your Booked Ticket From The Main Menu");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(590, 920, 700, 14);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("** Unique Code can be used to see your ticket details in 'Check Flight Details' Tab on the Home Page ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 860, 1010, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1490, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
TF1.setEditable(false);
TF2.setEditable(false);
TF3.setEditable(false);
TF4.setEditable(false);
TF5.setEditable(false);
TF6.setEditable(false);
TF7.setEditable(false);
TF8.setEditable(false);
TF9.setEditable(false);
TF10.setEditable(false);
TF11.setEditable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void RESERVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESERVEActionPerformed
try{
    
   String name=TF1.getText(); 
   String cno=TF2.getText();
   String airline=TF3.getText();
   String type=TF4.getText();
   String seat=TF5.getText();
   String depart=TF6.getText();
   String date=TF7.getText();
   String origin=TF8.getText();
   String end=TF9.getText();
   int amt=Integer.parseInt(TF10.getText());
   String payment=TF11.getText();
   int uno=Integer.parseInt(TF12.getText());
   Class.forName("java.sql.DriverManager"); 
   Connection con = DriverManager.getConnection("jdbc:mysql://localhost/flight", "root","1234"); 
   Statement st = con.createStatement();
  String query="INSERT INTO reserved VALUES('"+name+"','"+cno+"','"+airline+"','"+seat+"','"+depart+"','"+date+"','"+origin+"','"+end+"','"+payment+"','"+uno+"');"; 
  st.executeUpdate(query);
  JOptionPane.showMessageDialog(this,"FLIGHT RESERVED , HAVE A NICE DAY !");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_RESERVEActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
new MainForm().setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton RESERVE;
    public static javax.swing.JTextField TF1;
    public static javax.swing.JTextField TF10;
    public static javax.swing.JTextField TF11;
    private javax.swing.JTextField TF12;
    public static javax.swing.JTextField TF2;
    public static javax.swing.JTextField TF3;
    public static javax.swing.JTextField TF4;
    public static javax.swing.JTextField TF5;
    public static javax.swing.JTextField TF6;
    public static javax.swing.JTextField TF7;
    public static javax.swing.JTextField TF8;
    public static javax.swing.JTextField TF9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
