
import java.awt.Font;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
public class FlightDetails extends javax.swing.JFrame {

    /**
     * Creates new form FlightDetails
     */
    public FlightDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        NEXT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        T1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Airline", "Departure", "Terminal", "Cost", "Type", "From", "Destination"
            }
        ));
        T1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        T1.setRowHeight(30);
        T1.setRowMargin(2);
        jScrollPane1.setViewportView(T1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 1380, 390);

        NEXT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NEXT);
        NEXT.setBounds(610, 700, 230, 90);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 52)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FLIGHT  SCHEDULE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 70, 490, 56);

        LOGOUT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(1140, 10, 280, 40);

        BACK.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(20, 10, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -90, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.println(""+T1.getSelectedRows());
        NEXT.setVisible(false);
JTableHeader header = T1.getTableHeader();
Font f=new Font("Calibri",Font.BOLD|Font.ITALIC,18);
header.setFont(f);
if(T1.getRowCount()==0){
    JOptionPane.showMessageDialog(null,"No Flights Available!!!!");
new BookFlights().setVisible(true);
dispose();
}
else if(T1.getRowCount()>0){
    if(T1.getSelectedRows()==null){
        JOptionPane.showMessageDialog(null,"Please Select Flight!!!");
    }
else
      NEXT.setVisible(true);  
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
        new SeatBooking().setVisible(true);
        dispose();
        int row=T1.getSelectedRow();
        Date date = (Date) T1.getModel().getValueAt(row,0) ;
        String airline = (String) T1.getModel().getValueAt(row,1) ;
        String time = (String) T1.getModel().getValueAt(row,2) ;
        int cost = (int) T1.getModel().getValueAt(row,4) ;
        SeatBooking.TF1.setText(airline);
        SeatBooking.TF2.setText(""+date);
        SeatBooking.TF3.setText(time);
        SeatBooking.TF4.setText(""+cost);

        // TODO add your handling code here:
    }//GEN-LAST:event_NEXTActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        new MainForm().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new BookFlights().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton NEXT;
    public static javax.swing.JTable T1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
