

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kaustubh
 */
public class SeatBooking extends javax.swing.JFrame {

    /**
     * Creates new form SeatBooking
     */
    public SeatBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        NEXT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TF6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Airline :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 90, 210, 44);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Date :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 140, 190, 44);

        TF1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF1);
        TF1.setBounds(770, 90, 360, 36);

        TF2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF2);
        TF2.setBounds(770, 140, 360, 36);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setText("Time :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 190, 200, 44);

        TF3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF3);
        TF3.setBounds(770, 190, 360, 36);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setText("Base Price (Per Passenger) :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 240, 420, 40);

        TF4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF4);
        TF4.setBounds(770, 240, 360, 36);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setText("No. of Passengers :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 340, 320, 44);

        TF5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF5);
        TF5.setBounds(770, 340, 360, 36);

        buttonGroup2.add(RB1);
        RB1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        RB1.setText("ECONOMY CLASS");
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });
        getContentPane().add(RB1);
        RB1.setBounds(310, 460, 300, 53);

        buttonGroup2.add(RB2);
        RB2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        RB2.setText("BUSINESS CLASS");
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });
        getContentPane().add(RB2);
        RB2.setBounds(830, 460, 320, 53);

        NEXT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NEXT);
        NEXT.setBounds(651, 760, 170, 73);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setText("Total Amount :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 553, 240, 40);

        TF6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        TF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF6ActionPerformed(evt);
            }
        });
        getContentPane().add(TF6);
        TF6.setBounds(780, 549, 420, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PAYMENT METHOD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 36))); // NOI18N

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        R1.setText("Visa Card");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        R2.setText("Master Card");

        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        R3.setText("Net Banking");

        buttonGroup1.add(R4);
        R4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        R4.setText("Paytm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R4)
                    .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(R1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 620, 320, 230);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*Total Amount Is Inclusive Of All Additional Charges (Rs.500/-)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 1010, 565, 25);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("**Business Class Will Cost Rs.2000 Extra Than Economy Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 1050, 530, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel9.setText("Passenger Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 290, 310, 44);

        TF7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF7);
        TF7.setBounds(770, 290, 360, 36);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel10.setText("Contact No.:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 390, 250, 44);

        TF8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(TF8);
        TF8.setBounds(770, 390, 360, 36);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 52)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BOOKING DETAILS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(520, 0, 480, 64);

        LOGOUT.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(LOGOUT);
        LOGOUT.setBounds(1140, 10, 280, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("** Total Amount Includes Taxes Rs.500/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(870, 800, 510, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/313904.jpg"))); // NOI18N
        jLabel12.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel12.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -140, 1920, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
TF1.setEditable(false);
TF2.setEditable(false);
TF3.setEditable(false);
TF4.setEditable(false);
TF6.setEditable(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
if(TF5.getText()==null){
    JOptionPane.showMessageDialog(null,"Please Enter No. Of Passengers");
}
else if(R1.isSelected()==false && R2.isSelected()==false && R3.isSelected()==false && R4.isSelected()==false){
    JOptionPane.showMessageDialog(null,"Please Select Payment Option");
}
else if(TF7.getText()==null){
    JOptionPane.showMessageDialog(null,"Please Enter Passenger Name");
}
else if(TF8.getText()==null){
    JOptionPane.showMessageDialog(null,"Please Enter Contact No.");
}
else if(RB1.isSelected()==false && RB2.isSelected()==false){
    JOptionPane.showMessageDialog(null,"Please Select Class");
}
else{
    new ConfirmDetails().setVisible(true);
    dispose();
ConfirmDetails.TF7.setText(""+TF2.getText());
ConfirmDetails.TF6.setText(""+TF3.getText());
ConfirmDetails.TF5.setText(""+TF5.getText());
ConfirmDetails.TF1.setText(""+TF7.getText());
ConfirmDetails.TF2.setText(""+TF8.getText());
ConfirmDetails.TF3.setText(""+TF1.getText());
ConfirmDetails.TF10.setText(""+TF6.getText());
if(BookFlights.R1.isSelected()){
ConfirmDetails.TF8.setText(""+BookFlights.CB1.getSelectedItem());
ConfirmDetails.TF9.setText(""+BookFlights.CB2.getSelectedItem());
}
else if(BookFlights.R2.isSelected()){
ConfirmDetails.TF8.setText(""+BookFlights.CB3.getSelectedItem());
ConfirmDetails.TF9.setText(""+BookFlights.CB4.getSelectedItem());    
}

if(RB1.isSelected()){
    ConfirmDetails.TF4.setText("Economy Class");
}
else if(RB2.isSelected()){
    ConfirmDetails.TF4.setText("Business Class");
}
if(R1.isSelected()){
    ConfirmDetails.TF11.setText("Visa Card");
}
else if(R2.isSelected()){
    ConfirmDetails.TF11.setText("Master Card");
}
else if(R3.isSelected()){
    ConfirmDetails.TF11.setText("Net Banking");
}
else if(R4.isSelected()){
    ConfirmDetails.TF11.setText("Paytm");
}
    
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_NEXTActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void TF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF6ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
int no=Integer.parseInt(TF5.getText());
int price=Integer.parseInt(TF4.getText());
int total=no*price;
total=total+500;
TF6.setText(""+total);
        // TODO add your handling code here:
    }//GEN-LAST:event_RB1ActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
int no=Integer.parseInt(TF5.getText());
int price=Integer.parseInt(TF4.getText());
int total=no*price;
total=total+500+(no*2000);
TF6.setText(""+total);
        // TODO add your handling code here:
    }//GEN-LAST:event_RB2ActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        new MainForm().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton NEXT;
    public javax.swing.JRadioButton R1;
    public javax.swing.JRadioButton R2;
    public javax.swing.JRadioButton R3;
    public javax.swing.JRadioButton R4;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    public static javax.swing.JTextField TF1;
    public static javax.swing.JTextField TF2;
    public static javax.swing.JTextField TF3;
    public static javax.swing.JTextField TF4;
    public static javax.swing.JTextField TF5;
    public static javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
